#!/bin/bash

#$1: path to .blog file
name=$(basename $1 .blog)

scp -i ~/.ssh/id_zmhanhamserveruser $1 zmhanham@192.241.155.95:/tmp/
ssh -i ~/.ssh/id_zmhanhamserveruser zmhanham@192.241.155.95 createblogpost /tmp/$name.blog
